### ISSUE TITLE
Pol vi bug

### ISSUE THREAD

**Issue by awesterb** [bwesterb/pol#16]
```$ pol vi

An unhandled exception occured:

   Traceback (most recent call last):
     File "/usr/local/lib/python2.7/site-packages/pol/main.py", line 1318, in _run_command
       return self.args.func()
     File "/usr/local/lib/python2.7/site-packages/pol/main.py", line 1256, in cmd_vi
       pol.vi.main(self)
     File "/usr/local/lib/python2.7/site-packages/pol/vi.py", line 230, in main
       VisualPol(program).main()
     File "/usr/local/lib/python2.7/site-packages/pol/vi.py", line 172, in main
       self.loop.run()
     File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 286, in run
       self._run()
     File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 384, in _run
       self.event_loop.run()
     File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 788, in run
       self._loop()
     File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 825, in _loop
       self._watch_files[fd]()
     File "/usr/local/lib/python2.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
       event_loop, callback, self.get_available_raw_input())
     File "/usr/local/lib/python2.7/site-packages/urwid/raw_display.py", line 502, in parse_input
       callback(processed, processed_codes)
     File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 411, in _update
       self.process_input(keys)
     File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 517, in process_input
       something_handled |= bool(self.unhandled_input(k))
     File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 563, in unhandled_input
       return self._unhandled_input(input)
     File "/usr/local/lib/python2.7/site-packages/pol/vi.py", line 116, in unhandled_input
       elif not self.query.keypress((0,), key):
     File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 1481, in keypress
       if self.valid_char(key):
     File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 1126, in valid_char
       return is_wide_char(ch,0) or (len(ch)==1 and ord(ch) >= 32)
   TypeError: is_wide_char: Argument "text" is not a string.
```

**Comment by bwesterb** [comment]
Wat deed je om deze exception te krijgen?

**Comment by awesterb** [comment]
De console een tijdje open laten staan.
