### ISSUE TITLE
Error importing KeepassX db

### ISSUE THREAD

**Issue by zupo** [bwesterb/pol#9]
```
An unhandled exception occured:

   Traceback (most recent call last):
     File "/usr/local/lib/python2.7/site-packages/pol/main.py", line 1273, in _run_command
       return self.args.func()
     File "/usr/local/lib/python2.7/site-packages/pol/main.py", line 1150, in cmd_import_keepass
       the_container.save()
     File "/usr/local/lib/python2.7/site-packages/pol/safe.py", line 403, in save
       self.main_slice.store(self.list_key, main_pt, annex=annex)
     File "/usr/local/lib/python2.7/site-packages/pol/safe.py", line 520, in store
       raise ValueError("`value' too large")
   ValueError: `value' too large
```

**Comment by zupo** [comment]
One possibility is to display the key & value, and offer to skip.

**Comment by bwesterb** [comment]
Thanks for reporting the problem.   I should make this error message more user friendly.  You have to many entries to fit in the default size of the container.   (Actually, it's the combined size of the entries.)  Are you sure there are no unnecessarily large entries in there?  You can show the entries while importing by adding `-vv` after `pol`.  Another hack is to increase the size of your safe using the `-N` parameter to `init`.  Default is 1024.  Larger will make pol slower to rerandomize after each operation.  Be warned: you will need to overwrite your existing  container.  If you already have something in there, you can use `pol import` and `pol export`.

**Comment by zupo** [comment]
After removing the "trash" folder in KeepassX DB, the import finished successful for 425 items.

But the safe is broken apparenly. I get the following error for list, edit, etc. The safe was empty before import.

```
An unhandled exception occured:

   Traceback (most recent call last):
     File "/usr/local/lib/python2.7/site-packages/pol/main.py", line 1273, in _run_command
       return self.args.func()
     File "/usr/local/lib/python2.7/site-packages/pol/main.py", line 950, in cmd_edit
       for container in self._open_containers(safe, password):
     File "/usr/local/lib/python2.7/site-packages/pol/safe.py", line 678, in open_containers
       on_move_append_entries)
     File "/usr/local/lib/python2.7/site-packages/pol/safe.py", line 707, in _open_container_with_access_data
       main_slice.value))
     File "/usr/local/lib/python2.7/site-packages/pol/serialization.py", line 34, in string_to_son
       tmp = zlib.decompress(s[1:])
   error: Error -5 while decompressing data: incomplete or truncated stream
```

**Comment by bwesterb** [comment]
Can you create a new safe and try the import again, but this time adding `-vv` directly after `pol`?  Please copy the output after you removed your usernames and passwords.  Please double check you removed those.  I am interested in the lines like

```
8018 DEBUG pol.serialization son_to_string: original 2705; gzipped: 2289
8018 DEBUG pol.serialization son_to_string: original 5568; gzipped: 4282
8018 DEBUG pol.safe Slice.store: storing @206; 162 blocks; 4283/20376B
8144 DEBUG pol.safe Slice.store:  ... done in 0.126 (1286.7 block/s)
```

**Comment by zupo** [comment]
Hmmm. Cannot reproduce.

**Comment by bwesterb** [comment]
I will try to reproduce the bug you hit.
